[package]
name = "ncbi_nuccore_rs"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
thiserror = {version = "2.0.17"}
reqwest = { version = "0.13.1"}
indicatif = {version = "0.18.3"}
clap = {version = "4.5.54", features = ["derive"]}
